// pages/api/products.js

export const cookProducts = {
  AlManasef: {
    category: 'AlManasef',
    items: [
      {
        id: 'طبخ1',
        imgUrl: '/pufema.png',
        title: 'بوفيه مفتوح / كافة خدمات الطبخ والمناسبات',
        price: '0',
        type: 'sweets',
      },
      {
        id: 'طبخ2',
        imgUrl: '/mansafmola.png',
        title: 'منسف فريكة وموزات لحم',
        price: '0',
        type: 'sweets',
      },
      {
        id: 'طبخ3',
        imgUrl: '/biryani.png',
        title: 'برياني',
        price: '0',
        type: 'sweets',
      },

      {
        id: 'طبخ5',
        imgUrl: '/kabselah.png',
        title: 'خاروف محشي',
        price: '0',
        type: 'sweets',
      },
      {
        id: 'طبخ6',
        imgUrl: '/kabselah.png',
        title: 'كبسة لحم',
        price: '0',
        type: 'sweets',
      },
      {
        id: 'طبخ7',
        imgUrl: '/yaprakla.png',
        title: 'يبرق مع اللحم',
        price: '0',
        type: 'sweets',
      },

      {
        id: 'طبخ9',
        imgUrl: '/sayadiye.png',
        title: 'صيادية سمك',
        price: '0',
        type: 'sweets',
      },

      {
        id: 'طبخ12',
        imgUrl: '/frike.png',
        title: 'فريكة لحم موزات',
        price: '0',
        type: 'sweets',
      },
    ],
  },
  'Oriental cooking': {
    category: 'Oriental cooking',
    items: [
      {
        id: 'طبخ11',
        imgUrl: '/maklube.png',
        title: 'مقلوبة',
        price: '0',
        type: 'sweets',
      },
      {
        id: 'طبخ10',
        imgUrl: '/awzi.png',
        title: 'اوزي - برك جبنة/لحمة',
        price: '0',
        type: 'sweets',
      },
    ],
  },
  Appetizers: {
    category: 'Appetizers',
    items: [
      {
        id: 'طبخ4',
        imgUrl: '/yalanci.png',
        title: 'يالنجي',
        price: '0',
        type: 'sweets',
      },
      {
        id: 'طبخ8',
        imgUrl: '/hrakas.png',
        title: 'حراق اصبعو',
        price: '0',
        type: 'sweets',
      },
      {
        id: 'طبخ13',
        imgUrl: '/kaba.png',
        title: 'كبة',
        price: '0',
        type: 'sweets',
      },
    ],
  },
};

export const foodProducts = {
  'Sanabel honey': {
    category: 'Sanabel honey',
    items: [
      {
        id: 'أزهار جبلية 950',
        imgUrl: '/azhar975.jpg',
        title: 'عسل أزهار جبلية 975 غرام',
        description: 'أزهار جبلية ارتفاع 1500 متر',
        price: '435',
        type: 'food',
      },
      {
        id: 'أزهار جبلية 950',
        imgUrl: '/azhar975.jpg',
        title: 'عسل أزهار جبلية 975 غرام',
        description: 'أزهار جبلية ارتفاع 2500 متر',
        price: '475',
        type: 'food',
      },

      {
        id: 'الاشواك1',
        imgUrl: '/aswak975.jpg',
        title: 'عسل الشوكيات 975 غرام',
        description: 'عسل تركي طبيعي',
        price: '415',
        type: 'food',
      },
      {
        id: 'الاشواك2',
        imgUrl: '/aswak475.jpg',
        title: 'عسل الشوكيات 475 غرام',
        description: 'عسل تركي طبيعي',
        price: '210',
        type: 'food',
      },
      {
        id: 'الصنوبر1',
        imgUrl: '/sanawbae975.jpg',
        title: 'عسل الصنوبر 975 غرام',
        description: 'عسل الصنوبر الطبيعي',
        price: '350',
        type: 'food',
      },
      {
        id: 'الصنوبر2',
        imgUrl: '/sanawbar475.jpg',
        title: 'عسل الصنوبر 475 غرام',
        description: 'عسل الصنوبر الطبيعي',
        price: '180',
        type: 'food',
      },
      {
        id: 'الحمضيات1',
        imgUrl: '/hamdiyat975.jpg',
        title: 'عسل زهرة الحمضيات 975 غرام',
        description: 'عسل تركي طبيعي',
        price: '275',
        type: 'food',
      },
      {
        id: 'الحمضيات2',
        imgUrl: '/hamdiyat475.jpg',
        title: 'عسل زهرة الحمضيات 475 غرام',
        description: 'عسل تركي طبيعي',
        price: '140',
        type: 'food',
      },
      {
        id: 'ابيض1',
        imgUrl: '/abyad975.jpg',
        title: 'عسل أبيض 975 غرام',
        description: 'رحيق أزهار الساحل',
        price: '415',
        type: 'food',
      },
      {
        id: 'ابيض2',
        imgUrl: '/abyad475.jpg',
        title: 'عسل أبيض 430 غرام',
        description: 'رحيق أزهار الساحل',
        price: '210',
        type: 'food',
      },
      {
        id: 'سدر1',
        imgUrl: '/sadir975.jpg',
        title: 'عسل السدر 975 غرام',
        description: 'عسل تركي طبيعي',
        price: '445',
        type: 'food',
      },
      {
        id: 'سدر2',
        imgUrl: '/sadir475.jpg',
        title: 'عسل السدر 475 غرام',
        description: 'عسل تركي طبيعي',
        price: '225',
        type: 'food',
      },
      {
        id: 'مزيج1',
        imgUrl: '/mazig975.jpg',
        title: 'عسل مزيج الأزهار 975 غرام',
        description: 'عسل تركي طبيعي',
        price: '385',
        type: 'food',
      },
      {
        id: 'مزيج2',
        imgUrl: '/mazig475.jpg',
        title: 'عسل مزيج الأزهار 475 غرام',
        description: 'عسل تركي طبيعي',
        price: '195',
        type: 'food',
      },
      {
        id: 'البركة1',
        imgUrl: '/soda975.jpg',
        title: 'عسل زهرةالحبة السوداء 975 غرام',
        description: 'عسل تركي طبيعي (حبة البركة)',
        price: '545',
        type: 'food',
      },
      {
        id: 'البركة2',
        imgUrl: '/soda475.jpg',
        title: 'عسل زهرةالحبة السوداء 475 غرام',
        description: 'عسل تركي طبيعي (حبة البركة)',
        price: '275',
        type: 'food',
      },
      {
        id: 'الزلوع1',
        imgUrl: '/zallo975.jpg',
        title: 'عسل زهرة الزلوع 975 غرام',
        description: 'عسل تركي طبيعي',
        price: '495',
        type: 'food',
      },
      {
        id: 'الزلوع2',
        imgUrl: '/zallo475.jpg',
        title: 'عسل زهرة الزلوع 475 غرام',
        description: 'عسل تركي طبيعي',
        price: '250',
        type: 'food',
      },
      {
        id: 'غذاء ملكي1',
        imgUrl: '/malaki475.jpg',
        title: 'عسل الغذاء الملكي 475 غرام',
        description: 'مع الغذاء الملكي والجنسينغ',
        price: '410',
        type: 'food',
      },
      {
        id: 'غذاء ملكي114',
        imgUrl: '/aslasiww.jpg',
        title: 'عسل خلطة منتجات الخلية 475 غرام',
        description: 'غبار الطلع - عكبر - زنجبيل - قرفة',
        price: '475',
        type: 'food',
      },
      {
        id: 'الكستناء1',
        imgUrl: '/kastana475.jpg',
        title: 'أزهار الكستنا والزيزفون 475 غرام',
        description: 'من أشجار الكستناء وأزهار الزيزفون',
        price: '320',
        type: 'food',
      },
      {
        id: 'بشهده1',
        imgUrl: '/sahad1.jpg',
        title: 'عسل طبيعي بالشهد',
        description: 'من أزهار الحمضيات',
        price: '415',
        type: 'food',
      },
      {
        id: 'الطلع1',
        imgUrl: '/talia125.jpg',
        title: 'غبار الطلع 125 غرام',
        description: 'حبوب اللقاح',
        price: '95',
        type: 'food',
      },
      {
        id: 'عكبر1',
        imgUrl: '/akbar10.jpg',
        title: 'عكبر النحل 10 غرام',
        description: 'صمغ النحل أو البروبوليس',
        price: '95',
        type: 'food',
      },
      {
        id: 'ملكي غذاء1',
        imgUrl: '/kimalaki10.jpg',
        title: 'غذاء ملكات النحل 10 غرام',
        description: 'غذاء الملكات الطبيعي',
        price: '325',
        type: 'food',
      },
    ],
  },
  'olive oil': {
    category: 'olive oil',
    items: [
      {
        id: 'زيت 1 لتر',
        imgUrl: '/litir1.jpg',
        title: 'زيت 1 لتر',
        description: 'زيت بكر نوع أول',
        price: '115',
        type: 'food',
      },
      {
        id: 'زيت 5 لتر',
        imgUrl: '/litir5.jpg',
        title: 'زيت 5 لتر',
        description: 'زيت بكر نوع أول',
        price: '565',
        type: 'food',
      },
      {
        id: 'زيت 10 لتر',
        imgUrl: '/litir10.jpg',
        title: 'زيت 10 لتر',
        description: 'زيت بكر نوع أول',
        price: '1110',
        type: 'food',
      },
      {
        id: 'زيت 18 لتر',
        imgUrl: '/litir18.jpg',
        title: 'زيت 18 لتر',
        description: 'زيت بكر نوع أول',
        price: '1960',
        type: 'food',
      },
    ],
  },

  kishka: {
    category: 'kishka',
    items: [
      {
        id: 'الكشك1',
        imgUrl: '/kaskagr.jpg',
        title: 'الكشك',
        description: 'كيلو غرام من الكشك الطبيعي',
        price: '140',
        type: 'food',
      },
      {
        id: 'الكشك2',
        imgUrl: '/kaskagr.jpg',
        title: 'الكشك',
        description: '500 غرام من الكشك الطبيعي',
        price: '70',
        type: 'food',
      },
    ],
  },

  'Qamar alDin': {
    category: 'Qamar alDin',
    items: [
      {
        id: 'قمر1',
        imgUrl: '/mismis.jpg',
        title: 'لوح المشمش',
        description: ' أجود أنواع قمر الدين 300GR',
        price: '35',
        type: 'food',
      },
      {
        id: 'قمر2',
        imgUrl: '/mango.jpg',
        title: 'لوح المانغو',
        description: ' أجود أنواع قمر الدين 300GR',
        price: '35',
        type: 'food',
      },
      {
        id: 'قمر3',
        imgUrl: '/fraz.jpg',
        title: 'لوح فريز',
        description: ' أجود أنواع قمر الدين 300GR',
        price: '35',
        type: 'food',
      },
      {
        id: 'قمر4',
        imgUrl: '/burtukal.jpg',
        title: 'لوح البرتقال',
        description: ' أجود أنواع قمر الدين 300GR',
        price: '35',
        type: 'food',
      },
      {
        id: 'قمر5',
        imgUrl: '/mumas.jpg',
        title: 'مكعبات المشمش',
        description: 'مكعبات قمر الدين الشهية 500GR',
        price: '110',
        type: 'food',
      },
      {
        id: 'قمر8',
        imgUrl: '/mufraz.jpg',
        title: 'مكعبات الفريز',
        description: 'مكعبات قمر الدين الشهية 500GR',
        price: '110',
        type: 'food',
      },
      {
        id: 'قمر6',
        imgUrl: '/mubart.jpg',
        title: 'مكعبات البرتقال',
        description: 'مكعبات قمر الدين الشهية 500GR',
        price: '110',
        type: 'food',
      },
      {
        id: 'قمر7',
        imgUrl: '/mumanc.jpg',
        title: 'مكعبات المانجو',
        description: 'مكعبات قمر الدين الشهية 500GR',
        price: '110',
        type: 'food',
      },

      {
        id: 'قمر9',
        imgUrl: '/mucav.jpg',
        title: 'مكعبات الجوافة',
        description: 'مكعبات قمر الدين الشهية 500GR',
        price: '110',
        type: 'food',
      },
    ],
  },
  coffee: {
    category: 'coffee',
    items: [
      {
        id: 'قهوة1',
        imgUrl: '/kaex.jpg',
        title: 'قهوة بريميوم اكسترا',
        description: '250GR',
        price: '75',
        type: 'food',
      },
      {
        id: 'قهوة2',
        imgUrl: '/hewa.jpg',
        title: 'قهوة هيل وسط',
        description: '250GR',
        price: '70',
        type: 'food',
      },
      {
        id: 'قهوة3',
        imgUrl: '/sadaaa.jpg',
        title: 'قهوة سادة بدون هيل',
        description: '250GR',
        price: '65',
        type: 'food',
      },
    ],
  },
  obesity: {
    category: 'obesity',
    items: [
      {
        id: 'سمنة1',
        imgUrl: '/samangr.jpg',
        title: 'السمن الحيواني',
        description: 'أفضل أنواع السمن الحيواني (البقري) 850GR',
        price: '290',
        type: 'food',
      },
    ],
  },

  olive: {
    category: 'olive',
    items: [
      {
        id: 'زيتون أخضر',
        imgUrl: '/OlivePost1.png',
        title: 'زيتون أخضر',
        description: 'أفضل أنواع الزيتون 650GR',
        price: '70',
        type: 'food',
      },
      {
        id: 'زيتون أسود',
        imgUrl: '/OlivePost2.png',
        title: 'زيتون أسود',
        description: 'أفضل أنواع الزيتون 650GR',
        price: '80',
        type: 'food',
      },
      {
        id: 'زيتون سلطة اكسترا',
        imgUrl: '/OlivePost3.png',
        title: 'زيتون سلطة اكسترا',
        description: 'أفضل أنواع الزيتون 950GR',
        price: '90',
        type: 'food',
      },
    ],
  },

  'cream pistachio': {
    category: 'cream pistachio',
    items: [
      {
        id: 'كريمة-الفستق',
        imgUrl: '/kremafi.jpg',
        title: 'كريمة الفستق',
        description: 'كريمة الفستق القابلة للدهن 200GR',
        price: '85',
        type: 'food',
      },
    ],
  },
  'rose jam': {
    category: 'rose jam',
    items: [
      {
        id: 'مربى-الورد1',
        imgUrl: '/mrabaward.jpg',
        title: 'مربى الورد 800 غرام',
        description: 'الورد الجوري الطبيعي',
        price: '110',
        type: 'food',
      },
      {
        id: 'مربى-الورد2',
        imgUrl: '/waerd.jpg',
        title: 'مربى الورد 450 غرام',
        description: 'الورد الجوري الطبيعي',
        price: '65',
        type: 'food',
      },
    ],
  },
};

export const sweetsProducts = {
  Arab: {
    category: 'Arab',
    items: [
      {
        id: 'عربي1',
        imgUrl: '/fiska1000.png',
        title: 'مشكل فستق وكاجو',
        description: '1000 غرام',
        price: '550',
        type: 'sweets',
      },

      {
        id: 'عربي20',
        imgUrl: '/fika750.png',
        title: 'مشكل فستق وكاجو',
        description: '750 غرام',
        price: '415',
        type: 'sweets',
      },
      {
        id: 'عربي2',
        imgUrl: '/fika500.png',
        title: 'مشكل فستق وكاجو',
        description: '500 غرام',
        price: '275',
        type: 'sweets',
      },
      {
        id: 'عربي3',
        imgUrl: '/fika250.png',
        title: 'مشكل فستق وكاجو',
        description: '250 غرام',
        price: '175',
        type: 'sweets',
      },
      {
        id: 'عربي6',
        imgUrl: '/fika100.png',
        title: 'مشكل فستق كاجو',
        description: '100 غرام',
        price: '90',
        type: 'sweets',
      },
      {
        id: 'عربي5',
        imgUrl: '/fikass1000.png',
        title: 'مشكل فستق وكاجو بالعسل الملكي',
        description: '1000 غرام',
        price: '740',
        type: 'sweets',
      },
      {
        id: 'عربي13',
        imgUrl: '/malika500.png',
        title: 'مشكل فستق وكاجو بالعسل الملكي',
        description: '500 غرام',
        price: '370',
        type: 'sweets',
      },
      {
        id: 'عربي17',
        imgUrl: '/eksta1000.png',
        title: 'مشكل فستق اكسترا',
        description: '1000 غرام',
        price: '670',
        type: 'sweets',
      },

      {
        id: 'عربي8',
        imgUrl: '/baklava500.png',
        title: 'بقلاوة بالفستق',
        description: '500 غرام',
        price: '225',
        type: 'sweets',
      },
      {
        id: 'عربي15',
        imgUrl: '/fasta500.png',
        title: 'آسية بالفستق الحلبي',
        description: '500 غرام',
        price: '350',
        type: 'sweets',
      },

      {
        id: 'عربي19',
        imgUrl: '/sakae500.png',
        title: 'كول وشكور',
        description: '500 غرام',
        price: '335',
        type: 'sweets',
      },
      {
        id: 'عربي11',
        imgUrl: '/halap500.png',
        title: 'أصابع بالفستق الحلبي',
        description: '500 غرام',
        price: '335',
        type: 'sweets',
      },
      {
        id: 'عربي4',
        imgUrl: '/saba500.png',
        title: 'أصابع كاجو',
        description: '500 غرام',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'عربي10',
        imgUrl: '/mabruma500.png',
        title: 'مبرومة ترانشات',
        description: '500 غرام',
        price: '375',
        type: 'sweets',
      },
      {
        id: 'عربي14',
        imgUrl: '/asba500.png',
        title: 'عش البلبل بالفستق الحلبي',
        description: '500 غرام',
        price: '350',
        type: 'sweets',
      },
      {
        id: 'عربي22',
        imgUrl: '/tamriya600.png',
        title: 'تمرية',
        description: '600 غرام',
        price: '270',
        type: 'sweets',
      },

      {
        id: 'عربي7',
        imgUrl: '/kacu500.png',
        title: 'بلورية بالكاجو',
        description: '500 غرام',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'عربي9',
        imgUrl: '/kacobol500.png',
        title: 'بلورية كاجو بالعسل',
        description: '500 غرام',
        price: '250',
        type: 'sweets',
      },
      {
        id: 'عربي18',
        imgUrl: '/balham500.png',
        title: 'بلورية حمراء',
        description: '500 غرام',
        price: '350',
        type: 'sweets',
      },
      {
        id: 'عربي21',
        imgUrl: '/balbay500.png',
        title: 'بلورية بيضاء',
        description: '500 غرام',
        price: '350',
        type: 'sweets',
      },

      {
        id: 'عربي16',
        imgUrl: '/faysal500sa.png',
        title: 'فيصلية',
        description: '500 غرام',
        price: '250',
        type: 'sweets',
      },

      {
        id: 'عربي12',
        imgUrl: '/dolama1000.png',
        title: 'أصابع خضراء دولما',
        description: '1000 غرام',
        price: '620',
        type: 'sweets',
      },
    ],
  },
  nawashif: {
    category: 'nawashif',
    items: [
      {
        id: 'النواشف3',
        imgUrl: '/manawsaf500.png',
        title: 'مشكل نواشف',
        description: '500 غرام',
        price: '160',
        type: 'sweets',
      },
      {
        id: 'النواشف1',
        imgUrl: '/manavsa250.png',
        title: 'مشكل نواشف',
        description: '250 غرام',
        price: '110',
        type: 'sweets',
      },
      {
        id: 'النواشف5',
        imgUrl: '/msana100.png',
        title: 'مشكل نواشف',
        description: '100 غرام',
        price: '55',
        type: 'sweets',
      },
      {
        id: 'النواشف7',
        imgUrl: '/mayax50.png',
        title: 'معمول عجوة كعب الغزال',
        description: '500 غرام',
        price: '160',
        type: 'sweets',
      },
      {
        id: 'النواشف9',
        imgUrl: '/kazua250.png',
        title: 'معمول عجوة كعب الغزال',
        description: '250 غرام',
        price: '110',
        type: 'sweets',
      },
      {
        id: 'النواشف14',
        imgUrl: '/danab500.png',
        title: 'معمول عجوة طبعة سنابل',
        description: '500 غرام',
        price: '180',
        type: 'sweets',
      },
      {
        id: 'النواشف17',
        imgUrl: '/matsana500.png',
        title: 'معمول عجوة طبعة كبيرة',
        description: '500 غرام',
        price: '180',
        type: 'sweets',
      },
      {
        id: 'النواشف4',
        imgUrl: '/fahalep500.png',
        title: 'معمول بالفستق الحلبي',
        description: '500 غرام',
        price: '320',
        type: 'sweets',
      },
      {
        id: 'النواشف8',
        imgUrl: '/coz500.png',
        title: 'معمول بالجوز',
        description: '500 غرام',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'النواشف11',
        imgUrl: '/facoz500.png',
        title: 'معمول مشكل فستق وجوز',
        description: '500 غرام',
        price: '260',
        type: 'sweets',
      },

      {
        id: 'النواشف2',
        imgUrl: '/khkv500.png',
        title: 'معمول نارنج',
        description: '500 غرام',
        price: '180',
        type: 'sweets',
      },

      {
        id: 'النواشف6',
        imgUrl: '/masmas500.png',
        title: 'معمول المشمش',
        description: '500 غرام',
        price: '180',
        type: 'sweets',
      },
      {
        id: 'النواشف16',
        imgUrl: '/matin500.png',
        title: 'معمول التين',
        description: '500 غرام',
        price: '180',
        type: 'sweets',
      },

      {
        id: 'النواشف10',
        imgUrl: '/baraz.png',
        title: 'برازق',
        description: '500 غرام',
        price: '160',
        type: 'sweets',
      },

      {
        id: 'النواشف12',
        imgUrl: '/baraz200.png',
        title: 'برازق',
        description: '200 غرام',
        price: '110',
        type: 'sweets',
      },
      {
        id: 'النواشف13',
        imgUrl: '/kara500.png',
        title: 'غريبة',
        description: '500 غرام',
        price: '160',
        type: 'sweets',
      },
      {
        id: 'النواشف15',
        imgUrl: '/kara250.png',
        title: 'غريبة',
        description: '250 غرام',
        price: '110',
        type: 'sweets',
      },

      {
        id: 'النواشف18',
        imgUrl: '/lozfa.png',
        title: 'فلورنتين اللوز',
        description: 'سعر الكغ',
        price: '350',
        type: 'sweets',
      },
      {
        id: 'النواشف26',
        imgUrl: '/lozka.png',
        title: 'فلورنتين الفستق',
        description: 'سعر الكغ',
        price: '450',
        type: 'sweets',
      },

      {
        id: 'النواشف23',
        imgUrl: '/bavard.png',
        title: 'بتيفور وردة',
        description: '500 غرام',
        price: '120',
        type: 'sweets',
      },
      {
        id: 'النواشف28',
        imgUrl: '/batitart.png',
        title: 'بتيفور تارت',
        description: '550 غرام',
        price: '180',
        type: 'sweets',
      },
      {
        id: 'النواشف19',
        imgUrl: '/tartmsa.png',
        title: 'بتيفور تارت مشكل',
        description: '500 غرام',
        price: '180',
        type: 'sweets',
      },

      {
        id: 'النواشف25',
        imgUrl: '/batisable.png',
        title: 'بتيفور سابليه مشكل',
        description: '500 غرام',
        price: '165',
        type: 'sweets',
      },

      {
        id: 'النواشف27',
        imgUrl: '/sadamsak.png',
        title: 'بتيفور سادة مشكل',
        description: '500 غرام',
        price: '150',
        type: 'sweets',
      },

      {
        id: 'النواشف20',
        imgUrl: '/halkommas.png',
        title: 'راحة حلقوم مشكل',
        description: '500 غرام',
        price: '175',
        type: 'sweets',
      },
      {
        id: 'النواشف24',
        imgUrl: '/noba.png',
        title: 'مشكل نوغا',
        description: '500 غرام',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'النواشف21',
        imgUrl: '/lozsokola.png',
        title: 'أصابع لوز بالشوكولا',
        description: '450 غرام',
        price: '175',
        type: 'sweets',
      },
      {
        id: 'النواشف22',
        imgUrl: '/layalisam.png',
        title: 'ليالي الشام',
        description: 'سعر الكغ',
        price: '220',
        type: 'sweets',
      },
    ],
  },
  'Deluxe sweets with cream': {
    category: 'Deluxe sweets with cream',
    items: [
      {
        id: 'قشاطي12',
        imgUrl: '/kataue.png',
        title: 'قطايف بالقشطة',
        description: 'سعر القطعة',
        price: '25',
        type: 'sweets',
      },
      {
        id: 'قشاطي16',
        imgUrl: '/katayecoz.png',
        title: 'قطايف بالجوز',
        description: 'سعر القطعة',
        price: '27',
        type: 'sweets',
      },
      {
        id: 'قشاطي26',
        imgUrl: '/asafiri.png',
        title: 'قطايف عصافيري بالقشطة',
        description: 'سعر الكغ',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'قشاطي13',
        imgUrl: '/karibakas.png',
        title: 'غريبة بالقشطة',
        description: 'سعر القطعة',
        price: '20',
        type: 'sweets',
      },
      {
        id: 'قشاطي14',
        imgUrl: '/warbat.png',
        title: 'وربات بالقشطة',
        description: 'سعر القطعة',
        price: '24',
        type: 'sweets',
      },
      {
        id: 'قشاطي17',
        imgUrl: '/barbat.png',
        title: 'وردات بالقشطة',
        description: 'سعر القطعة',
        price: '22',
        type: 'sweets',
      },
      {
        id: 'قشاطي24',
        imgUrl: '/namora.png',
        title: 'نمورة بالقشطة',
        description: 'سعر الكغ',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'قشاطي25',
        imgUrl: '/nahs.png',
        title: 'نهش',
        description: 'سعر الكغ',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'قشاطي15',
        imgUrl: '/magsosa.png',
        title: 'مغشوشة بالقشطة',
        description: 'سعر كغ',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'قشاطي27',
        imgUrl: '/bulbulka.png',
        title: 'عش البلبل بالقشطة',
        description: 'سعر الكغ',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'قشاطي20',
        imgUrl: '/knafeam.png',
        title: 'كنافة أم النارين',
        description: 'سعر الكغ',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'قشاطي6',
        imgUrl: '/faysal.png',
        title: 'فيصلية',
        description: 'سعر الكغ',
        price: '500',
        type: 'sweets',
      },
      {
        id: 'قشاطي31',
        imgUrl: '/asmaliyaas.png',
        title: 'عصملية بالقشطة',
        description: 'سعر كغ',
        price: '200',
        type: 'sweets',
      },

      {
        id: 'قشاطي18',
        imgUrl: '/nabls.png',
        title: 'نابلسية',
        description: 'سعر كغ',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'قشاطي23',
        imgUrl: '/madloka.png',
        title: 'مدلوقة بالقشطة',
        description: 'سعر الكغ',
        price: '200',
        type: 'sweets',
      },
      {
        id: 'قشاطي19',
        imgUrl: '/madrokaak.png',
        title: 'مفروكة بالقشطة',
        description: 'سعر القطعة',
        price: '30',
        type: 'sweets',
      },

      {
        id: 'قشاطي21',
        imgUrl: '/madrokaak.png',
        title: 'مفروكة بالقشطة',
        description: 'سعر الكغ',
        price: '220',
        type: 'sweets',
      },
      {
        id: 'قشاطي22',
        imgUrl: '/halavab.png',
        title: 'حلاوة الجبن',
        description: 'سعر الكغ',
        price: '160',
        type: 'sweets',
      },

      {
        id: 'قشاطي28',
        imgUrl: '/sacoz.png',
        title: 'شعيبيات بالجوز',
        description: 'سعر القطعة',
        price: '27',
        type: 'sweets',
      },
      {
        id: 'قشاطي29',
        imgUrl: '/sabiyatkas.png',
        title: 'شعيبيات بالقشطة',
        description: 'سعر القطعة',
        price: '25',
        type: 'sweets',
      },
      {
        id: 'قشاطي30',
        imgUrl: '/bozaka.png',
        title: 'بوظا عربي بالقشطة والفستق اكسترا',
        description: 'سعر كغ',
        price: '220',
        type: 'sweets',
      },

      {
        id: 'قشاطي7',
        imgUrl: '/bakladas.png',
        title: 'بقلاوة بالفستق',
        description: 'سعر الكغ',
        price: '500',
        type: 'sweets',
      },
      {
        id: 'قشاطي10',
        imgUrl: '/baklacoz.png',
        title: 'بقلاوة بالجوز',
        description: 'سعر الكغ',
        price: '400',
        type: 'sweets',
      },
      {
        id: 'قشاطي9',
        imgUrl: '/midyada.png',
        title: 'ميديا بالفستق',
        description: 'سعر الكغ',
        price: '320',
        type: 'sweets',
      },

      {
        id: 'قشاطي1',
        imgUrl: '/eswara.png',
        title: 'إسوارة الست',
        description: 'سعر الكغ',
        price: '250',
        type: 'sweets',
      },

      {
        id: 'قشاطي4',
        imgUrl: '/harisa.png',
        title: 'هريسة بالفستق',
        description: '1000 غرام',
        price: '190',
        type: 'sweets',
      },
      {
        id: 'قشاطي8',
        imgUrl: '/mokasarat.png',
        title: 'هريسة بالمكسرات',
        description: '1000 غرام',
        price: '190',
        type: 'sweets',
      },
      {
        id: 'قشاطي2',
        imgUrl: '/harisa.png',
        title: 'هريسة باللوز',
        description: 'سعر الكغ',
        price: '170',
        type: 'sweets',
      },

      {
        id: 'قشاطي3',
        imgUrl: '/isbanya.png',
        title: 'إسبانيّة',
        description: 'سعر الكغ',
        price: '120',
        type: 'sweets',
      },

      {
        id: 'قشاطي11',
        imgUrl: '/malokmoak.png',
        title: 'ملوكية بالمكسرات',
        description: '600 غرام',
        price: '240',
        type: 'sweets',
      },
      {
        id: 'قشاطي5',
        imgUrl: '/kiile.png',
        title: 'كلير',
        description: 'سعر القطعة',
        price: '23',
        type: 'sweets',
      },
    ],
  },
};
